package com.xiaori.ui.screens.settings

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import com.xiaori.R

@Composable
fun getAllSearchableSettings(): List<Triple<String, String, String>> {
    return listOf(
            Triple(stringResource(R.string.about), "About", "settings/about"),
            Triple(stringResource(R.string.account), "Account", "settings/account"),
            Triple(stringResource(R.string.action_exported), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.action_logout), "Account", "settings/account"),
            Triple(stringResource(R.string.advanced_login), "Account", "settings/account"),
            Triple(stringResource(R.string.ai_api_key), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_base_url), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_deepl_formality), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_deepl_formality_default), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_deepl_formality_less), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_deepl_formality_more), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_lyrics_translation), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_model), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_claude_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_deepl_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_gemini_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_mistral_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_nvidia_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_openai_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_openrouter_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_perplexity_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_xai_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_setup_guide), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_target_language), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_translation_literal), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_translation_literal_desc), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_translation_mode), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_translation_transcribed), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_translation_transcribed_desc), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.album_text), "Content", "settings/content"),
            Triple(stringResource(R.string.albums), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.app_language), "Content", "settings/content"),
            Triple(stringResource(R.string.app_update_uptodate), "System Update", "settings/update"),
            Triple(stringResource(R.string.app_updates_title), "System Update", "settings/update"),
            Triple(stringResource(R.string.appearance), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.apple_music), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.apple_music_lyrics_blur), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.apple_music_lyrics_blur_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.apple_music_style), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.apple_music_style_letter), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.artist_page_settings), "Content", "settings/content"),
            Triple(stringResource(R.string.artists), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.audio_normalization), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.audio_offload), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.audio_offload_description), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.audio_offload_disabled_by_crossfade), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.audio_quality), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.auto_download_on_like), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.auto_download_on_like_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.auto_load_more), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.auto_load_more_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.auto_playlists), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.auto_skip_next_on_error), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.auto_skip_next_on_error_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.auto_update_check), "System Update", "settings/update"),
            Triple(stringResource(R.string.auto_update_check_subtitle), "System Update", "settings/update"),
            Triple(stringResource(R.string.backup_restore), "Backup & Restore", "settings/backup_restore"),
            Triple(stringResource(R.string.big), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.cache_size_warning_confirm), "Storage", "settings/storage"),
            Triple(stringResource(R.string.cache_size_warning_message), "Storage", "settings/storage"),
            Triple(stringResource(R.string.cache_size_warning_title), "Storage", "settings/storage"),
            Triple(stringResource(R.string.cd_back), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.cd_palette_item), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.center), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.clear_all_downloads), "Storage", "settings/storage"),
            Triple(stringResource(R.string.clear_downloaded_updates), "System Update", "settings/update"),
            Triple(stringResource(R.string.clear_downloaded_updates_desc), "System Update", "settings/update"),
            Triple(stringResource(R.string.clear_downloads_dialog), "Storage", "settings/storage"),
            Triple(stringResource(R.string.clear_image_cache), "Storage", "settings/storage"),
            Triple(stringResource(R.string.clear_image_cache_dialog), "Storage", "settings/storage"),
            Triple(stringResource(R.string.clear_listen_history), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.clear_listen_history_confirm), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.clear_search_history), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.clear_search_history_confirm), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.clear_song_cache), "Storage", "settings/storage"),
            Triple(stringResource(R.string.clear_song_cache_dialog), "Storage", "settings/storage"),
            Triple(stringResource(R.string.close), "Content", "settings/content"),
            Triple(stringResource(R.string.color_palette), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.commits), "System Update", "settings/update"),
            Triple(stringResource(R.string.config_proxy), "Content", "settings/content"),
            Triple(stringResource(R.string.content), "Content", "settings/content"),
            Triple(stringResource(R.string.content_country), "Content", "settings/content"),
            Triple(stringResource(R.string.content_language), "Content", "settings/content"),
            Triple(stringResource(R.string.crop_album_art), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.crop_album_art_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.crossfade), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.crossfade_beta_message), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.crossfade_beta_title), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.crossfade_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.crossfade_duration), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.crossfade_gapless), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.crossfade_gapless_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.dark_theme_follow_system), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.default_), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.default_lib_chips), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.default_open_tab), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.default_style), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.density_restart_message), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.disable), "Storage", "settings/storage"),
            Triple(stringResource(R.string.disable_load_more_when_repeat_all), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.disable_load_more_when_repeat_all_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.disable_screenshot), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.disable_screenshot_desc), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.display_density), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.download_quality_title), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.downloaded_songs), "Storage", "settings/storage"),
            Triple("Echo Brain", "Echo Brain (Beta)", "settings/echo_brain"),
            Triple("Learning Level", "Echo Brain (Beta)", "settings/echo_brain"),
            Triple("Analyzed Artists", "Echo Brain (Beta)", "settings/echo_brain"),
            Triple("Discovered Genres", "Echo Brain (Beta)", "settings/echo_brain"),
            Triple("Total Interactions", "Echo Brain (Beta)", "settings/echo_brain"),
            Triple(stringResource(R.string.echo_equalizer), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.echo_equalizer_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.xiaori_1), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.xiaori_canvas), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.xiaori_canvas_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.enable), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.enable_authentication), "Content", "settings/content"),
            Triple(stringResource(R.string.enable_better_lyrics), "Content", "settings/content"),
            Triple(stringResource(R.string.enable_better_lyrics_desc), "Content", "settings/content"),
            Triple(stringResource(R.string.enable_dynamic_theme), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.enable_high_refresh_rate), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.enable_high_refresh_rate_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.enable_kugou), "Content", "settings/content"),
            Triple(stringResource(R.string.enable_lossless_audio), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.enable_lrclib), "Content", "settings/content"),
            Triple(stringResource(R.string.enable_proxy), "Content", "settings/content"),
            Triple(stringResource(R.string.enable_similar_content), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.enable_simpmusic), "Content", "settings/content"),
            Triple(stringResource(R.string.enable_simpmusic_desc), "Content", "settings/content"),
            Triple(stringResource(R.string.enable_swipe_thumbnail), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.export_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.export_directory), "Storage", "settings/storage"),
            Triple(stringResource(R.string.fade), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.filter_library), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.filter_local), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.follow_theme), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.general), "Content", "settings/content"),
            Triple(stringResource(R.string.general), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.glow), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.glow_animated), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.google_cast), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.google_cast_description), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.gradient), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.grid_cell_size), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.hide_explicit), "Content", "settings/content"),
            Triple(stringResource(R.string.hide_player_thumbnail), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.hide_player_thumbnail_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.hide_status_bar_on_fullscreen), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.hide_status_bar_on_fullscreen_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.hide_video_songs), "Content", "settings/content"),
            Triple(stringResource(R.string.hide_youtube_shorts), "Content", "settings/content"),
            Triple(stringResource(R.string.history_duration), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.home), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.image_cache), "Storage", "settings/storage"),
            Triple(stringResource(R.string.ip_version_auto), "Content", "settings/content"),
            Triple(stringResource(R.string.ip_version_ipv4), "Content", "settings/content"),
            Triple(stringResource(R.string.ip_version_ipv6), "Content", "settings/content"),
            Triple(stringResource(R.string.karaoke), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.keep_screen_on_when_player_is_expanded), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.last_song_listened), "Content", "settings/content"),
            Triple(stringResource(R.string.left), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.legacy_icon), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.legacy_icon_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.line_by_line_dialog_desc), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.line_by_line_dialog_title), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.line_by_line_option_desc), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.line_by_line_option_title), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.listen_history), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.listen_together_in_top_bar), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.listen_together_in_top_bar_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.live_mesh), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.login), "Account", "settings/account"),
            Triple(stringResource(R.string.logout_clear_data), "Account", "settings/account"),
            Triple(stringResource(R.string.logout_dialog_message), "Account", "settings/account"),
            Triple(stringResource(R.string.logout_dialog_title), "Account", "settings/account"),
            Triple(stringResource(R.string.logout_keep_data), "Account", "settings/account"),
            Triple(stringResource(R.string.logs_heading), "Content", "settings/content"),
            Triple(stringResource(R.string.lossless_audio_warning), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.lyrics), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.lyrics), "Content", "settings/content"),
            Triple(stringResource(R.string.lyrics_animation_metro), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_animation_style), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_auto_scroll), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_click_change), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_glow_effect), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_glow_effect_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_line_spacing), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_provider_priority), "Content", "settings/content"),
            Triple(stringResource(R.string.lyrics_provider_priority_desc), "Content", "settings/content"),
            Triple(stringResource(R.string.lyrics_romanization), "Content", "settings/content"),
            Triple(stringResource(R.string.lyrics_romanization_cyrillic), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_romanize_as_main), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_romanize_belarusian), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_romanize_bulgarian), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_romanize_chinese), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_romanize_hindi), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_romanize_japanese), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_romanize_korean), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_romanize_kyrgyz), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_romanize_macedonian), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_romanize_punjabi), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_romanize_russian), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_romanize_serbian), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_romanize_title), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_romanize_ukrainian), "Romanization", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_swipe_to_change_song), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_swipe_to_change_song_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_text_position), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_text_size), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_thumbnail_play_pause), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_thumbnail_play_pause_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.lyrics_v2_fluid), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.max_image_cache_size), "Storage", "settings/storage"),
            Triple(stringResource(R.string.max_song_cache_size), "Storage", "settings/storage"),
            Triple(stringResource(R.string.mini_player), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.miniplayer_background_style), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.misc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.misc), "Content", "settings/content"),
            Triple(stringResource(R.string.misc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.misc), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.more_content), "Account", "settings/account"),
            Triple(stringResource(R.string.network_ip_version), "Content", "settings/content"),
            Triple(stringResource(R.string.none), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.not_set), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.not_set), "Storage", "settings/storage"),
            Triple(stringResource(R.string.palette_amber), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_blue), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_blue_grey), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_brown), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_crimson), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_cyan), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_deep_orange), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_deep_purple), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_dynamic), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_green), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_grey), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_indigo), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_light_green), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_lime), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_orange), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_purple), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_rose), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_sky_blue), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_teal), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.palette_yellow), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.pause_listen_history), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.pause_music_when_media_is_muted), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.pause_search_history), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.persistent_queue), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.persistent_queue_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.persistent_shuffle_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.persistent_shuffle_title), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.playback_logs), "Content", "settings/content"),
            Triple(stringResource(R.string.playback_logs_desc), "Content", "settings/content"),
            Triple(stringResource(R.string.player), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.player), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.player_and_audio), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.player_background_blur), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.player_background_style), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.player_buttons_style), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.player_slider_style), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.playlists), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.prevent_duplicate_tracks_in_queue), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.prevent_duplicate_tracks_in_queue_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.primary_color_style), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.privacy), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.proxy), "Content", "settings/content"),
            Triple(stringResource(R.string.proxy_password), "Content", "settings/content"),
            Triple(stringResource(R.string.proxy_type), "Content", "settings/content"),
            Triple(stringResource(R.string.proxy_url), "Content", "settings/content"),
            Triple(stringResource(R.string.proxy_username), "Content", "settings/content"),
            Triple(stringResource(R.string.queue), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.quick_picks), "Content", "settings/content"),
            Triple(stringResource(R.string.randomize_home_order), "Content", "settings/content"),
            Triple(stringResource(R.string.randomize_home_order_desc), "Content", "settings/content"),
            Triple(stringResource(R.string.remember_shuffle_and_repeat), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.remember_shuffle_and_repeat_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.reset), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.restart), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.restart_required), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.resume_on_bluetooth_connect), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.right), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.rotating_thumbnail), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.rotating_thumbnail_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.save), "Content", "settings/content"),
            Triple(stringResource(R.string.search_history), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.seek_seconds_addup), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.seek_seconds_addup_description), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.sensitivity_percentage), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.set_quick_picks), "Content", "settings/content"),
            Triple(stringResource(R.string.settings_section_player_content), "Account", "settings/account"),
            Triple(stringResource(R.string.show_album_canvas), "Content", "settings/content"),
            Triple(stringResource(R.string.show_album_canvas_desc), "Content", "settings/content"),
            Triple(stringResource(R.string.show_artist_background_video), "Content", "settings/content"),
            Triple(stringResource(R.string.show_artist_background_video_desc), "Content", "settings/content"),
            Triple(stringResource(R.string.show_artist_description), "Content", "settings/content"),
            Triple(stringResource(R.string.show_artist_monthly_listeners), "Content", "settings/content"),
            Triple(stringResource(R.string.show_artist_subscriber_count), "Content", "settings/content"),
            Triple(stringResource(R.string.show_artist_video), "Content", "settings/content"),
            Triple(stringResource(R.string.show_artist_video_desc), "Content", "settings/content"),
            Triple(stringResource(R.string.show_cached_playlist), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.show_comment_button), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.show_comment_button_description), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.show_downloaded_playlist), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.show_liked_playlist), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.show_top_playlist), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.show_uploaded_playlist), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.shuffle_playlist_first), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.shuffle_playlist_first_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.similar_content_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.skip_silence), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.skip_silence_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.skip_silence_instant), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.skip_silence_instant_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.slide), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.slim), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.small), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.song_cache), "Storage", "settings/storage"),
            Triple(stringResource(R.string.songs), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.squiggly), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.standard_lyrics_blur), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.stop_music_on_task_clear), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.storage), "Storage", "settings/storage"),
            Triple(stringResource(R.string.swipe_sensitivity), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.swipe_song_to_add), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.swipe_song_to_remove), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.system_default), "Content", "settings/content"),
            Triple(stringResource(R.string.system_update), "System Update", "settings/update"),
            Triple(stringResource(R.string.tertiary_color_style), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.theme), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.theme_colors), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.theme_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.theme_mode), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.thumbnail_corner_radius), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.thumbnail_corner_radius_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.token_adv_login_description), "Account", "settings/account"),
            Triple(stringResource(R.string.token_hidden), "Account", "settings/account"),
            Triple(stringResource(R.string.token_shown), "Account", "settings/account"),
            Triple(stringResource(R.string.top_length), "Content", "settings/content"),
            Triple(stringResource(R.string.unlimited), "Storage", "settings/storage"),
            Triple(stringResource(R.string.update_available), "System Update", "settings/update"),
            Triple(stringResource(R.string.update_notifications), "System Update", "settings/update"),
            Triple(stringResource(R.string.update_notifications_subtitle), "System Update", "settings/update"),
            Triple(stringResource(R.string.update_settings_title), "System Update", "settings/update"),
            Triple(stringResource(R.string.version), "System Update", "settings/update"),
            Triple(stringResource(R.string.view_commit_history), "System Update", "settings/update"),
            Triple(stringResource(R.string.wavy), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.yt_sync), "Account", "settings/account"),

            // Hardcoded Settings Missed by Generator
            Triple("Import from Spotify", "Backup & Restore", "settings/spotify_import"),
            Triple("Import from local file", "Backup & Restore", "settings/backup_restore"),
            Triple("Import 'm3u' Playlist", "Backup & Restore", "settings/backup_restore"),
            Triple("Import 'csv' Playlist", "Backup & Restore", "settings/backup_restore"),
            Triple("Local Backup", "Backup & Restore", "settings/backup_restore"),
            Triple("Equalizer", "Player and audio", "settings/equalizer"),
            Triple("Integrations", "Settings", "settings/integrations"),
            Triple("Listen Together", "Integrations", "settings/integrations/listen_together"),
            Triple("YouLyPlus", "Content", "settings/content"),
            Triple("PaxSenix", "Content", "settings/content"),
            Triple("Apple Music Inspired", "Appearance", "settings/appearance")
    )
}
